#!/usr/bin/env bash

set -euo pipefail

pacman -Sy \
	base-devel \
	git

curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

git clone https://aur.archlinux.org/1password.git

pushd 1password
makepkg -sir
popd

rm -rf 1password

