#!/usr/bin/env bash

set -euo pipefail

u ="$(uname -s)"


if [[ "$u" = "Linux" ]]; then
	pacman -Sy \
		base-devel \
		git

	curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

	git clone https://aur.archlinux.org/1password.git

	pushd 1password
	makepkg -sir
	popd

	rm -rf 1password
	
elif [[ "$u" = "Darwin" ]]; then
	brew install --cask 1password
else
	echo "Oh, you thought you wouldn't want to use this anywhere else?"
fi

